CREATE TABLE b_shopvk_post
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	ACTIVE char(1) NOT NULL,
	CREATED datetime NOT NULL,
	LAST_MODIFIED datetime NOT NULL,
	SITE_ID char(2) NOT NULL,
	IBLOCK_ID int(11) NOT NULL,
	ELEMENT_ID int(11) NOT NULL,
	VK_OWNER_ID int(11) NOT NULL,
	VK_POST_ID int(11) NOT NULL,
	PRIMARY KEY pk_b_shopvk_post(ID)
);


CREATE TABLE b_shopvk_albums
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	ACTIVE char(1) NOT NULL,
	CREATED datetime NOT NULL,
	LAST_MODIFIED datetime NOT NULL,
	SITE_ID char(2) NOT NULL,
	IBLOCK_ID int(11) NOT NULL,
	SECTION_ID int(11) NOT NULL,
	SECTION_NAME varchar(255) NOT NULL,
	VK_OWNER_ID int(11) NOT NULL,
	VK_ALBUM_ID int(11) NOT NULL,
	VK_ALBUM_NAME varchar(255) NOT NULL,
	VK_ALBUM_CAPTION varchar(255) NOT NULL,
	PRIMARY KEY pk_b_shopvk_albums(ID)
);

CREATE TABLE b_shopvk_photos
(
	ID int(11) NOT NULL AUTO_INCREMENT,
	ACTIVE char(1) NOT NULL,
	CREATED datetime NOT NULL,
	LAST_MODIFIED datetime NOT NULL,
	SITE_ID char(2) NOT NULL,
	IBLOCK_ID int(11) NOT NULL,
	ELEMENT_ID int(11) NOT NULL,
	FILE_ID int(18) NOT NULL,
	VK_OWNER_ID int(11) NOT NULL,
	VK_ALBUM_ID int(11) NOT NULL,
	VK_PHOTO_ID int(11) NOT NULL,
	VK_PHOTO_CAPTION varchar(255) NOT NULL,	
	PRIMARY KEY pk_b_shopvk_photos(ID)
);
